#!/gearlock/bin/bash
clear
echo "#This is a package manager for gearlock files/extensions.
 
#Type 'list' to list all the available packages.
 
"

read -p "Welcome to Gpm >>>> " gpm

if [ $gpm = list ];then
clear
figlet -c Packages
echo "Mesa20.2
Lspeed
CloudFareDNS
Xapk-Installer
"
read -n 1 -s -r -p "Press Enter To Continue"
gpm #since it will be placed in system/bin/
fi
