#!/gearlock/bin/bash

        case $1 in 
            list) 
            clear
            figlet -c Packages
            echo "
            
--> Mesa20.2 by Hmtheboy154
--> CloudFareDNS by AXON
--> Xapk-Installer by JaxParrow
--> App-Backup-and-Restore by Jaxporrow
## MORE TO COME ##
            
            "
            read -n 1 -s -r -p "Press Enter To Continue "
            gpm #since its in /system/bin/
            ;;
            
            mesa20.2) echo "Downloading Mesa 20.2"
            cd /sdcard/Download/
            axel https://dl.dropbox.com/s/z6ksr4q1k1djwsa/Mesa20.2.6-LLVM10.gxp?dl=1
            read -n 1 -s -r -p "Download Complete!!-Press Enter To Continue "
            exit
            ;;
            
            cloudfaredns) echo "Downloading Fast Cloudfare DNS by AXON"
            cd /sdcard/Download/
            axel https://dl.dropbox.com/s/6zubh85vz0lfen1/CloudflareDNS4GearLock_2.7-IPv4_xerta555.gxp?dl=1
            read -n 1 -s -r -p "Download Complete!!-Press Enter To Continue "
            exit
            
            ;;
       
            *) echo "
            
>>> 'gpm list' to list the available Packages.
>>> 'gpm' + 'the name of the Package' to download a package
            
            "
            read -n 1 -s -r -p "Press Enter To Continue "
            gpm #since its in /system/bin/
            ;;
        esac
